# A small-talk on Imputation 

Imputation == Filling the missing data

In [1]:
import numpy as np

In [9]:
data = np.arange(1, 16, dtype= np.float64).reshape(5, 3)

In [10]:
data

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [12]:
data[1, 1] = np.nan
data[3, 0] = np.nan
data[3, 2] = np.nan

In [13]:
data

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.],
       [nan, 11., nan],
       [13., 14., 15.]])

###  

In [15]:
from sklearn.impute import SimpleImputer

In [25]:
imp = SimpleImputer(strategy= 'mean')

In [26]:
imp.fit(data)

SimpleImputer()

In [27]:
imp.transform(data)

array([[ 1.  ,  2.  ,  3.  ],
       [ 4.  ,  8.75,  6.  ],
       [ 7.  ,  8.  ,  9.  ],
       [ 6.25, 11.  ,  8.25],
       [13.  , 14.  , 15.  ]])

In [28]:
((1 + 4 + 7 + 13) / 4, (2 + 8 + 11 + 14) / 4, (3 + 6 + 9 + 15) / 4)

(6.25, 8.75, 8.25)

### AXIS = 1 not available!

That's it for imputer.  
Next up - we will demystify the Bayes theorem.